### ISSUE TITLE
Feedback for “Conclusion & Next Steps”

### ISSUE THREAD

**Issue by adamobrien4** [Ankr-network/ankr-docs#1140]
Your docs are out of date, AnkrscanProvider no longer exists, should be AnkrProvider. Also, add some docs with error codes please.

**Comment by raproid** [comment]
@adamobrien4 Thanks a lot! Changed the code snippets. Error codes are coming soon.

**Comment by raproid** [comment]
https://ankr.readme.io/reference/introduction if it helps, the code snippets under "Node" tab are working correctly and contain the right provider.

**Comment by raproid** [comment]
https://ankr.readme.io/reference/error-codes here are the errors and error codes for AAPI.

**Comment by raproid** [comment]
I'm closing this issue as done if you don't mind.
