### ISSUE TITLE
Feedback for “Token API” - ankr_getTokenHoldersCount

### ISSUE THREAD

**Issue by j-greig** [Ankr-network/ankr-docs#1321]
Is it possible to configure ankr_getTokenHoldersCount to sort the response by balance?

Surely it would make sense for the response to default to returning the biggest holders first...

I can see other methods have a "descOrder" boolean option.

Thanks :)

**Comment by raproid** [comment]
Sorry for the late reply. I got the answer a while back, I think, but other tasks took my focus away from it.
We don't have this feature in our plans for now.

**Comment by raproid** [comment]
I'm closing this issue due to lack of man-hours for now. Let's reopen it if we get to implement it in the future.
