### ISSUE TITLE
Gnosis Nethermind flags

### ISSUE THREAD

**Issue by emlautarom1** [Ankr-network/ankr-docs#1383]
Multiple RPC providers that support Gnosis are using Nethermind as a client, Ankr being one of those. There is an open ticket on Nethermind (https://github.com/NethermindEth/nethermind/issues/5936) related to the `trace_transaction` method where multiple RPC providers either return `Not Found` or fail with an exception, while Ankr is able to produce the correct result.

As part of the debugging process on Nethermind, it would be really useful if you could share which options are you using to run Nethermind in your public RPC (https://rpc.ankr.com/gnosis). The only information that we have right now is the result of `web3_clientVersion` which is `Nethermind/v1.20.1+9f39c0c7/linux-x64/dotnet7.0.9`, but this is not enough.

**Comment by mikekondratev** [comment]
Good day! We use the standard recommended settings for our Gnosis nodes. Most likely you are running a non-archived node. "receipt could not be found" is a generic answer which generally indicates that the node has not stored state for the transaction

**Comment by raproid** [comment]
No updates for 2 weeks, no comments to the Mike's answer. I'm closing the issue.
