### ISSUE TITLE
Feedback for “Avalanche RPC error”

### ISSUE THREAD

**Issue by ADcodeur** [Ankr-network/ankr-docs#1442]
Hello Ankr Team,

I get this error when calling the avalanche c chain rpc endpoint when I want to get the balance of an address. The same method works well with other EVM enpoints:

rpc: service/method request ill-formed: "eth_getBalance"

Regards

**Comment by galleon8** [comment]
Hi ADcodeur.

For Avalanche, we support both EVM-compatible endpoint and C-chain endpoint. `eth_getBalance` method is available ONLY with the EVM-compatible one. C-chain uses Avalnche-specific methods and has its own way of building requests, which you could check out [here](https://www.ankr.com/docs/rpc-service/chains/chains-api/avalanche/#c-chain-methods).

Best regards,
Ankr team

**Comment by ADcodeur** [comment]
Hi,

Oh yes I missed that part, thank you for your response!

Regards
