### ISSUE TITLE
The breadcrumbs are not clickable and don't work

### ISSUE THREAD

**Issue by Dhaiwat10** [Ankr-network/ankr-docs#400]
The breadcrumbs in our docs don't do anything when we click on them. Aren't they supposed to be clickable? They should let me easily go back to anything in that list when I click on it. But right now it's just a piece of text that doesn't do anything. Only the home button works.

https://user-images.githubusercontent.com/39617427/173757348-50370c94-cf96-47ec-b12a-609049f1a09e.mp4

**Comment by jcstein** [comment]
Another case for [nextra.vercel.app](https://nextra.vercel.app)

**Comment by raproid** [comment]
We're on Nextra now and the breadcrumbs are still not clickable. Adding it to the docs roadmap.

**Comment by raproid** [comment]
Breadcrumbs are clickable in the Nextra 2.2.16, but they are implemented in a way that doesn't look desirable for our setup, so not implementing it. Closing the issue.
