### ISSUE TITLE
Bug bounty

### ISSUE THREAD

**Issue by akincibor** [Ankr-network/ankr-docs#828]
Hi,

Do you give bounty for XSS injection ?

Best regards,
Akincibor.eth

**Comment by raproid** [comment]
Hi,

We have a bounty program: https://immunefi.com/bounty/ankr/

You can also contact mikhail.levin@ankr.com with more details if you want a more specific answer, as conditions may vary depending on the severity of the bug. Mikhail approved me posting here his email.

**Comment by akincibor** [comment]
Hi,

I know but the only scope of the bug bounty program is www.ankr.com/staking/*

I will contact Mikhail.

Best regards,
Akincibor.eth

**Comment by raproid** [comment]
Assuming you copied the email address to contact, I'm closing this issue.

**Comment by akincibor** [comment]
Confirmed, bounty will be paid "ONLY" for the bugs on this specific page www.ankr.com/staking/.
No bounty for bugs on www.ankr.com and subdomains.

![FWHN23vUAAMn5sf](https://user-images.githubusercontent.com/99909324/202539792-53d1d685-b4f2-45e9-ab85-6635bc0ac17d.jpeg)
