### ISSUE TITLE
Feedback for “Token API”

### ISSUE THREAD

**Issue by Standarten** [Ankr-network/ankr-docs#913]
Hello my dear Dev colleagues,

I recently tried your Advanced Token API and it's great!

There's one optimization idea for your 'ankr_getTokenPriceHistory'-method though, as I sometimes didn't receive the right token prices on certain requests.
I suggest, that you could implement a 'pairAddress' parameter besides or instead of the already used 'contractAddress' parameter to specify exactly of which token pair liquidity pool the token price has to be fetched from (as there are often multiple and also inofficial pools with totally different token prices) .

Greetings from Germany
Peet

**Comment by galleon8** [comment]
Hello Peet,

Thanks a lot for your feedback, idea, and kind words regarding our product.

We're planning to rework our pricing calculation by indexing all the LPs price updates (as opposed to the current 1 update per block per token). So, we are thinking in the same direction.

Thanks once again for your feedback and kind regards from the Dev team.
